// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['main']['App']['GetAll']();
}

export function GetTodos(arg1) {
  return window['go']['main']['App']['GetTodos'](arg1);
}

export function Post(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Post'](arg1, arg2, arg3, arg4);
}
