// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Delete(arg1:string):Promise<void>;

export function GetAll():Promise<Array<main.A>>;

export function GetTodos(arg1:string):Promise<Array<main.Todo>>;

export function Post(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;
